name       : libicu
version    : '72.1'
release    : 24
source     :
    - https://github.com/unicode-org/icu/releases/download/release-72-1/icu4c-72_1-src.tgz : a2d2d38217092a7ed56635e34467f92f976b370e20182ad325edea6681a71d68
license    : MIT
component  : xorg.fonts
emul32     : yes
summary    : International Components for Unicode
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
patterns   :
    - devel :
        - /usr/share/icu
setup      : |
    pushd source
    %configure --disable-static
build      : |
    %make -C source
install    : |
    %make_install -C source
check      : |
    # some 32bit tests fail
    %make check -C source || :
