name       : libicu
version    : 59.1
release    : 12
source     :
    - http://download.icu-project.org/files/icu4c/59.1/icu4c-59_1-src.tgz : 7132fdaf9379429d004005217f10e00b7d2319d0fea22bdfddef8991c45b75fe
license    : MIT
component  : xorg.fonts
emul32     : yes
summary    : International Components for Unicode
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
patterns   :
    - devel :
        - /usr/share/icu
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-locale.h-with-glibc-2.26.patch
    %patch -p3 < $pkgfiles/security/cve-2017-14952.patch
    %patch -p3 < $pkgfiles/security/cve-2017-15422.patch
    pushd source
    %configure --disable-static
build      : |
    %make -C source
install    : |
    %make_install -C source
#check      : |
#    %make check -C source
