name       : libicu
version    : '57.1'
release    : 6
source     :
    - http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz : ff8c67cb65949b1e7808f2359f2b80f722697048e90e7cfc382ec1fe229e9581
license    :
    - MIT
summary    : International Components for Unicode
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
patterns   :
    - devel :
        - /usr/share/icu
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
setup      : |
    pushd source
    %configure --prefix=/usr --disable-static
build      : |
    pushd source
    %make
install    : |
    pushd source
    %make_install
