name       : libicu
version    : '58.2'
release    : 8
source     :
    - http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz : 2b0a4410153a9b20de0e20c7d8b66049a72aef244b53683d0d7521371683da0c
license    : MIT
component  : xorg.fonts
summary    : International Components for Unicode
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
emul32     : yes
patterns   :
    - devel :
        - /usr/share/icu
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-7867.patch
    pushd source
    %configure --prefix=/usr --disable-static
build      : |
    pushd source
    %make
install    : |
    pushd source
    %make_install
check      : |
    pushd source
    %make check
